/**
 * defaultModels 默认模型配置 — 按类型（文本/图像/视频/音频）定义各厂商预置模型列表和分组
 */
import type { GeneralModelConfig, ModelGroup, ModelOption } from '../../../types';

export type MediaModelKind = 'image' | 'video';

export interface MediaModelOption extends ModelOption {
  mediaKind: MediaModelKind;
  groupId: string;
  groupName: string;
}

export const defaultModelGroups: ModelGroup[] = [
  // ========================================
  // 文本生成模型
  // ========================================
  {
    id: 'apimart',
    name: 'APIMart',
    description: '一个 API 搞定一切——节省 30-70%',
    iconType: 'badge',
    badgeText: 'AM',
    models: [
      // ── 文本模型 ──
      {
        value: 'apimart/gpt-5.4',
        provider: 'apimart',
        label: 'GPT-5.4',
        description: '极致逻辑与推理性能',
        iconType: 'badge',
        badgeText: 'OA',
        nodeTypes: ['ai-text'],
      },
      {
        value: 'apimart/gpt-5.2',
        provider: 'apimart',
        label: 'GPT-5.2',
        description: '最新旗舰，顶尖推理与代码能力',
        iconType: 'badge',
        badgeText: 'OA',
        nodeTypes: ['ai-text'],
      },
      {
        value: 'apimart/gpt-5',
        provider: 'apimart',
        label: 'GPT-5',
        description: 'OpenAI 旗舰模型，增强推理',
        iconType: 'badge',
        badgeText: 'OA',
        nodeTypes: ['ai-text'],
      },
      {
        value: 'apimart/gpt-4o',
        provider: 'apimart',
        label: 'GPT-4o',
        description: '多模态旗舰，平衡性能与成本',
        iconType: 'badge',
        badgeText: 'OA',
        nodeTypes: ['ai-text'],
      },
      {
        value: 'apimart/claude-opus-4-7',
        provider: 'apimart',
        label: 'Claude Opus 4.7',
        description: 'Anthropic 最强推理模型',
        iconType: 'badge',
        badgeText: 'AN',
        nodeTypes: ['ai-text'],
      },
      {
        value: 'apimart/claude-sonnet-4-6',
        provider: 'apimart',
        label: 'Claude Sonnet 4.6',
        description: '高性价比复杂推理',
        iconType: 'badge',
        badgeText: 'AN',
        nodeTypes: ['ai-text'],
      },
      {
        value: 'apimart/gemini-3.5-flash',
        provider: 'apimart',
        label: 'Gemini 3.5 Flash',
        description: 'Google 最新多模态模型',
        iconType: 'badge',
        badgeText: 'GG',
        nodeTypes: ['ai-text'],
      },
      {
        value: 'apimart/gemini-3.1-pro-preview',
        provider: 'apimart',
        label: 'Gemini 3.1 Pro',
        description: 'Google 旗舰推理模型',
        iconType: 'badge',
        badgeText: 'GG',
        nodeTypes: ['ai-text'],
      },
      {
        value: 'apimart/deepseek-v4-pro',
        provider: 'apimart',
        label: 'DeepSeek V4 Pro',
        description: 'DeepSeek 最强模型，超长上下文',
        iconType: 'badge',
        badgeText: 'DS',
        nodeTypes: ['ai-text'],
      },
      {
        value: 'apimart/kimi-k2.5',
        provider: 'apimart',
        label: 'Kimi K2.5',
        description: '月之暗面最新版，超长上下文',
        iconType: 'badge',
        badgeText: 'KM',
        nodeTypes: ['ai-text'],
      },
      {
        value: 'apimart/kimi-k2-instruct',
        provider: 'apimart',
        label: 'Kimi K2',
        description: '月之暗面指令遵循模型',
        iconType: 'badge',
        badgeText: 'KM',
        nodeTypes: ['ai-text'],
      },
      {
        value: 'apimart/glm-5.1',
        provider: 'apimart',
        label: 'GLM-5.1',
        description: '智谱最新大语言模型',
        iconType: 'badge',
        badgeText: 'GL',
        nodeTypes: ['ai-text'],
      },
      {
        value: 'apimart/minimax-m2.5',
        provider: 'apimart',
        label: 'MiniMax M2.5',
        description: 'MiniMax 大语言模型',
        iconType: 'badge',
        badgeText: 'MM',
        nodeTypes: ['ai-text'],
      },
      {
        value: 'apimart/o4-mini',
        provider: 'apimart',
        label: 'o4-mini',
        description: 'OpenAI 推理模型，高性价比',
        iconType: 'badge',
        badgeText: 'OA',
        nodeTypes: ['ai-text'],
      },
      // ── 图片模型 ──
      {
        value: 'apimart/gemini-3.1-flash-image-preview',
        provider: 'apimart',
        label: 'Nano Banana 3.1',
        description: '最新 Nano Banana，最高画质',
        iconType: 'badge',
        badgeText: 'NB',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'apimart/gemini-3-pro-image-preview',
        provider: 'apimart',
        label: 'Nano Banana Pro',
        description: '专业级画质，光影渲染深度优化',
        iconType: 'badge',
        badgeText: 'NP',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'apimart/gemini-2.5-flash-image-preview',
        provider: 'apimart',
        label: 'Nano Banana',
        description: '极速版，支持独特创意风格呈现',
        iconType: 'badge',
        badgeText: 'ND',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'apimart/gpt-image-2',
        provider: 'apimart',
        label: 'GPT Image 2',
        description: 'OpenAI 图像生成，支持文生图与图生图',
        iconType: 'badge',
        badgeText: 'AM',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'apimart/imagen-4.0-apimart',
        provider: 'apimart',
        label: 'Imagen 4.0',
        description: 'Google 旗舰图像生成模型',
        iconType: 'badge',
        badgeText: 'GG',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'apimart/flux-2-pro',
        provider: 'apimart',
        label: 'Flux 2 Pro',
        description: 'Black Forest Labs 专业级生图',
        iconType: 'badge',
        badgeText: 'FL',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'apimart/qwen-image-2.0-pro',
        provider: 'apimart',
        label: 'Qwen Image 2.0 Pro',
        description: '通义千问专业图像生成',
        iconType: 'badge',
        badgeText: 'QW',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'apimart/z-image-turbo',
        provider: 'apimart',
        label: 'Z-Image-Turbo',
        description: '轻量快速生图，支持智能改写',
        iconType: 'badge',
        badgeText: 'ZI',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'apimart/grok-imagine-1.0-apimart',
        provider: 'apimart',
        label: 'Grok Imagine',
        description: 'xAI 图像生成模型',
        iconType: 'badge',
        badgeText: 'GR',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'apimart/midjourney',
        provider: 'apimart',
        label: 'Midjourney',
        description: 'Midjourney 图像生成',
        iconType: 'badge',
        badgeText: 'MJ',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'apimart/wan2.7-image-pro',
        provider: 'apimart',
        label: 'Wan 2.7 Pro',
        description: '进阶文生图与图像编辑',
        iconType: 'badge',
        badgeText: 'WA',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'apimart/seedream-4.0',
        provider: 'apimart',
        label: 'Seedream 4.0',
        description: '灵活图像功能，支持高分辨率',
        iconType: 'badge',
        badgeText: 'SD',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'apimart/seedream-4.5',
        provider: 'apimart',
        label: 'Seedream 4.5',
        description: '性能均衡的多模式图像生成',
        iconType: 'badge',
        badgeText: 'SD',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'apimart/seedream-5.0-lite',
        provider: 'apimart',
        label: 'Seedream 5.0 Lite',
        description: '轻量高效生图，支持 2K/3K',
        iconType: 'badge',
        badgeText: 'SD',
        nodeTypes: ['ai-image'],
      },
      // ── 视频模型 ──
      {
        value: 'apimart/doubao-seedance-2.0',
        provider: 'apimart',
        label: '豆包视频 2.0',
        description: '字节跳动最新视频生成',
        iconType: 'badge',
        badgeText: 'DB',
        nodeTypes: ['ai-video'],
      },
      {
        value: 'apimart/sora-2',
        provider: 'apimart',
        label: 'Sora 2',
        description: 'OpenAI 视频生成旗舰模型',
        iconType: 'badge',
        badgeText: 'OA',
        nodeTypes: ['ai-video'],
      },
      {
        value: 'apimart/veo3.1-quality',
        provider: 'apimart',
        label: 'Veo 3.1',
        description: 'Google 高质量视频生成',
        iconType: 'badge',
        badgeText: 'GG',
        nodeTypes: ['ai-video'],
      },
      {
        value: 'apimart/kling-v3',
        provider: 'apimart',
        label: 'Kling V3',
        description: '可灵最新视频生成模型',
        iconType: 'badge',
        badgeText: 'KL',
        nodeTypes: ['ai-video'],
      },
      {
        value: 'apimart/MiniMax-Hailuo-2.3',
        provider: 'apimart',
        label: '海螺 2.3',
        description: 'MiniMax 视频生成旗舰版',
        iconType: 'badge',
        badgeText: 'HL',
        nodeTypes: ['ai-video'],
      },
      {
        value: 'apimart/wan2.7',
        provider: 'apimart',
        label: 'Wan 2.7',
        description: '万兴视频生成，高画质输出',
        iconType: 'badge',
        badgeText: 'WA',
        nodeTypes: ['ai-video'],
      },
      {
        value: 'apimart/skyreels-v4-std',
        provider: 'apimart',
        label: 'SkyReels V4',
        description: 'SkyReels 视频生成模型',
        iconType: 'badge',
        badgeText: 'SR',
        nodeTypes: ['ai-video'],
      },
      {
        value: 'apimart/viduq3-pro',
        provider: 'apimart',
        label: 'Vidu Q3 Pro',
        description: 'Vidu 专业级视频生成',
        iconType: 'badge',
        badgeText: 'VD',
        nodeTypes: ['ai-video'],
      },
      {
        value: 'apimart/Omni-Flash-Ext',
        provider: 'apimart',
        label: 'Omni Flash',
        description: '全模态快速视频生成',
        iconType: 'badge',
        badgeText: 'OF',
        nodeTypes: ['ai-video'],
      },
      // ── 音频模型 ──
      {
        value: 'apimart/gpt-4o-mini-transcribe',
        provider: 'apimart',
        label: 'GPT-4o Mini 转录',
        description: 'OpenAI 语音转文字，高性价比',
        iconType: 'badge',
        badgeText: 'OA',
        nodeTypes: ['ai-audio'],
      },
      {
        value: 'apimart/gpt-4o-transcribe',
        provider: 'apimart',
        label: 'GPT-4o 转录',
        description: 'OpenAI 语音转文字，高精度',
        iconType: 'badge',
        badgeText: 'OA',
        nodeTypes: ['ai-audio'],
      },
      {
        value: 'apimart/gpt-4o-mini-tts',
        provider: 'apimart',
        label: 'GPT-4o Mini TTS',
        description: 'OpenAI 文字转语音，高性价比',
        iconType: 'badge',
        badgeText: 'OA',
        nodeTypes: ['ai-audio'],
      },
      {
        value: 'apimart/whisper-1',
        provider: 'apimart',
        label: 'Whisper',
        description: 'OpenAI 语音识别模型',
        iconType: 'badge',
        badgeText: 'OA',
        nodeTypes: ['ai-audio'],
      },
    ],
  },
  {
    id: 'volcengine',
    name: '火山方舟',
    description: 'Ark Seedream 图像生成 API',
    iconType: 'badge',
    badgeText: 'V',
    models: [
      // --- 文本模型 ---
      {
        value: 'volcengine/doubao-seed-2-0-pro-260215',
        provider: 'volcengine',
        label: 'doubao-seed-2-0-pro',
        description: '适合复杂文本生成与推理',
        iconType: 'badge',
        badgeText: 'DB',
        nodeTypes: ['ai-text'],
      },
      {
        value: 'volcengine/doubao-seed-2-0-lite-260428',
        provider: 'volcengine',
        label: 'doubao-seed-2-0-lite',
        description: '适合高频文本任务',
        iconType: 'badge',
        badgeText: 'DL',
        nodeTypes: ['ai-text'],
      },
      // --- 图片模型 ---
      {
        value: 'volcengine/doubao-seedream-5-0-pro-260628',
        provider: 'volcengine',
        label: 'Seedream 5.0 Pro',
        description: '旗舰生图模型，支持文生图/组图/多图参考，1K/2K',
        iconType: 'badge',
        badgeText: 'V',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'volcengine/doubao-seedream-5-0-lite-260128',
        provider: 'volcengine',
        label: 'Seedream 5.0 Lite',
        description: '轻量高效生图，支持 2K/3K/4K，输入+输出 ≤15 张',
        iconType: 'badge',
        badgeText: 'V',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'volcengine/doubao-seedream-4-5-251128',
        provider: 'volcengine',
        label: 'Seedream 4.5',
        description: '性能均衡的多模式图像生成，2K/4K',
        iconType: 'badge',
        badgeText: 'V',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'volcengine/doubao-seedream-4-0-250828',
        provider: 'volcengine',
        label: 'Seedream 4.0',
        description: '经典 Seedream 生图，支持 1K/2K/4K，可选极速模式',
        iconType: 'badge',
        badgeText: 'V',
        nodeTypes: ['ai-image'],
      },
      // --- 视频模型 ---
      {
        value: 'volcengine/doubao-seedance-2-0-260128',
        provider: 'volcengine',
        label: 'Seedance 2.0',
        description: '旗舰视频生成模型，支持多模态输入，4-15s',
        iconType: 'badge',
        badgeText: 'V',
        nodeTypes: ['ai-video'],
      },
      {
        value: 'volcengine/doubao-seedance-2-0-fast-260128',
        provider: 'volcengine',
        label: 'Seedance 2.0 Fast',
        description: '快速视频生成，性能与质量平衡，4-15s',
        iconType: 'badge',
        badgeText: 'V',
        nodeTypes: ['ai-video'],
      },
      {
        value: 'volcengine/doubao-seedance-2-0-mini-260615',
        provider: 'volcengine',
        label: 'Seedance 2.0 Mini',
        description: '轻量视频生成模型，4-15s',
        iconType: 'badge',
        badgeText: 'V',
        nodeTypes: ['ai-video'],
      },
      {
        value: 'volcengine/doubao-seedance-1-5-pro-251215',
        provider: 'volcengine',
        label: 'Seedance 1.5 Pro',
        description: '专业视频生成，支持样片模式/离线推理，4-12s',
        iconType: 'badge',
        badgeText: 'V',
        nodeTypes: ['ai-video'],
      },
      {
        value: 'volcengine/doubao-seedance-1-0-pro-250528',
        provider: 'volcengine',
        label: 'Seedance 1.0 Pro',
        description: '经典种子舞蹈视频生成，2-12s',
        iconType: 'badge',
        badgeText: 'V',
        nodeTypes: ['ai-video'],
      },
      {
        value: 'volcengine/doubao-seedance-1-0-pro-fast-251015',
        provider: 'volcengine',
        label: 'Seedance 1.0 Pro Fast',
        description: '快速经典视频生成，2-12s',
        iconType: 'badge',
        badgeText: 'V',
        nodeTypes: ['ai-video'],
      },
    ],
  },

  // ========================================
  // 图片生成专用供应商
  // ========================================

  // --- GRSAI ---
  {
    id: 'grsai',
    name: 'GRSAI',
    description: '高性能 AI 图像生成服务',
    iconType: 'badge',
    badgeText: 'GR',
    models: [
      {
        value: 'grsai/gpt-image-2',
        provider: 'grsai',
        label: 'GPT image 2',
        description: 'OpenAI 图像生成模型',
        iconType: 'badge',
        badgeText: 'GR',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'grsai/nanobanana',
        provider: 'grsai',
        label: 'Nanobanana',
        description: '基础模型',
        iconType: 'badge',
        badgeText: 'GR',
        nodeTypes: ['ai-image'],
        nbFamily: 'nanobanana',
      },
      {
        value: 'grsai/nanobanana-pro',
        provider: 'grsai',
        label: 'NanobananaPRO',
        description: '专业增强模型',
        iconType: 'badge',
        badgeText: 'GR',
        nodeTypes: ['ai-image'],
        nbFamily: 'nanobanana-pro',
      },
      {
        value: 'grsai/nanobanana-2',
        provider: 'grsai',
        label: 'Nanobanana2',
        description: '第二代模型',
        iconType: 'badge',
        badgeText: 'GR',
        nodeTypes: ['ai-image'],
        nbFamily: 'nanobanana-2',
      },
    ],
  },

  // --- 即梦/Dreamina ---
  {
    id: 'dreamina',
    name: '即梦',
    description: '官方 OAuth 登录，自动文生图/图生图/视频',
    iconType: 'badge',
    badgeText: 'JM',
    models: [
      {
        value: 'dreamina/4.0',
        provider: 'dreamina',
        label: '即梦4.0',
        description: '无图文生图 / 单图图生图',
        iconType: 'badge',
        badgeText: 'JM',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'dreamina/4.5',
        provider: 'dreamina',
        label: '即梦4.5',
        description: '综合性能均衡，推荐默认',
        iconType: 'badge',
        badgeText: 'JM',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'dreamina/4.7',
        provider: 'dreamina',
        label: '即梦4.7',
        description: '细节增强，生成更稳定',
        iconType: 'badge',
        badgeText: 'JM',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'dreamina/5.0',
        provider: 'dreamina',
        label: '即梦5.0',
        description: '新版模型，画面表现更强',
        iconType: 'badge',
        badgeText: 'JM',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'dreamina/seedance2.0fast',
        provider: 'dreamina',
        label: '即梦视频 Seedance2.0 Fast',
        description: '文生视频 / 图生视频，速度优先',
        iconType: 'badge',
        badgeText: 'JM',
        nodeTypes: ['ai-video'],
      },
      {
        value: 'dreamina/seedance2.0',
        provider: 'dreamina',
        label: '即梦视频 Seedance2.0',
        description: '文生视频 / 图生视频，质量优先',
        iconType: 'badge',
        badgeText: 'JM',
        nodeTypes: ['ai-video'],
      },
    ],
  },

  // --- RunningHUB 模型 ---
  {
    id: 'runninghub',
    name: 'RunningHUB模型',
    description: '模型 API：文生图/图生图/图片编辑',
    iconType: 'badge',
    badgeText: 'RH',
    models: [
      {
        value: 'runninghub/nanobanana',
        provider: 'runninghub',
        label: 'NanoBanana',
        description: '基础图像生成模型，版本可在模式中切换',
        iconType: 'badge',
        badgeText: 'NB',
        nodeTypes: ['ai-image'],
        nbFamily: 'nanobanana',
      },
      {
        value: 'runninghub/nanobanana-pro',
        provider: 'runninghub',
        label: 'BananaPRO',
        description: '专业级画质，版本可在模式中切换',
        iconType: 'badge',
        badgeText: 'BP',
        nodeTypes: ['ai-image'],
        nbFamily: 'nanobanana-pro',
      },
      {
        value: 'runninghub/nanobanana-2',
        provider: 'runninghub',
        label: 'Banana2',
        description: '新一代图像模型，版本可在模式中切换',
        iconType: 'badge',
        badgeText: 'B2',
        nodeTypes: ['ai-image'],
        nbFamily: 'nanobanana-2',
      },
      {
        value: 'runninghub/gpt-image-2',
        provider: 'runninghub',
        label: 'GPT image 2',
        description: 'OpenAI 图像生成模型，版本可在模式中切换',
        iconType: 'badge',
        badgeText: 'RH',
        nodeTypes: ['ai-image'],
        nbFamily: 'gpt-image-2',
      },
      {
        value: 'runninghub-model/youchuan-v81',
        provider: 'runninghub',
        label: 'Midjourney V8.1',
        description: 'RunningHub Midjourney 文生图 V8.1，支持主图和风格参考图',
        iconType: 'badge',
        badgeText: 'RH',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'runninghub-model/youchuan-v7',
        provider: 'runninghub',
        label: 'Midjourney V7',
        description: 'RunningHub Midjourney 文生图 V7，支持主图和风格参考图',
        iconType: 'badge',
        badgeText: 'RH',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'runninghub-model/youchuan-v6',
        provider: 'runninghub',
        label: 'Midjourney V6',
        description: 'RunningHub Midjourney 文生图 V6，支持主图、角色参考图和风格参考图',
        iconType: 'badge',
        badgeText: 'RH',
        nodeTypes: ['ai-image'],
      },
    ],
  },

  // --- RunningHUB 工作流 ---
  {
    id: 'runninghubwf',
    name: 'RunningHUB工作流',
    description: '工作流模板：替换/风格迁移，结果更可控',
    iconType: 'badge',
    badgeText: 'RW',
    models: [
      {
        value: 'runninghub/2041177685895946242',
        provider: 'runninghubwf',
        label: '人物替换图片编辑V3',
        description: '双图人物替换，支持目标/被替换图遮罩',
        iconType: 'badge',
        badgeText: 'RW',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'runninghub/2050313968069165058',
        provider: 'runninghubwf',
        label: '人物替换V2.1',
        description: '双图人物替换，支持目标/被替换图遮罩',
        iconType: 'badge',
        badgeText: 'RW',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'runninghub/1994718111704158209',
        provider: 'runninghubwf',
        label: '漫画转真人',
        description: '基于工作流把二次元角色转写实人像',
        iconType: 'badge',
        badgeText: 'RW',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'runninghub/2050306122774532097',
        provider: 'runninghubwf',
        label: 'Qwen-图像编辑',
        description: '多图指令编辑，适合人物/产品一致性、文字修改与姿势/深度控制',
        iconType: 'badge',
        badgeText: 'RW',
        nodeTypes: ['ai-image'],
      },
    ],
  },
];

/** 节点与对话共用的图片/视频模型目录，不包含工作流。 */
export function getMediaModelOptions(
  generalModels: GeneralModelConfig[] = [],
): MediaModelOption[] {
  const builtIn = defaultModelGroups.flatMap((group) => group.models.flatMap((model) => {
    if (model.provider === 'runninghubwf') return [];
    const supportsImage = model.nodeTypes.includes('ai-image');
    const supportsVideo = model.nodeTypes.includes('ai-video');
    const entries: MediaModelOption[] = [];
    const groupInfo = { groupId: group.id, groupName: group.name };
    if (supportsImage) entries.push({ ...model, ...groupInfo, mediaKind: 'image' });
    if (supportsVideo) entries.push({ ...model, ...groupInfo, mediaKind: 'video' });
    return entries;
  }));

  const custom: MediaModelOption[] = generalModels
    .filter((model) => model.category === 'image' || model.category === 'video')
    .map((model) => {
      const mediaKind: MediaModelKind = model.category === 'image' ? 'image' : 'video';
      return {
        value: `general/${model.id}`,
        provider: 'general',
        label: model.name,
        description: `ID: ${model.modelId}`,
        iconType: 'badge',
        badgeText: mediaKind === 'image' ? '图' : '视',
        nodeTypes: mediaKind === 'image' ? ['ai-image'] : ['ai-video'],
        mediaKind,
        groupId: 'general-models',
        groupName: '通用模型',
      };
    });

  const unique = new Map<string, MediaModelOption>();
  for (const model of [...builtIn, ...custom]) {
    unique.set(`${model.mediaKind}:${model.value}`, model);
  }
  return [...unique.values()];
}

export function findMediaModelOption(
  modelRef: string,
  generalModels: GeneralModelConfig[] = [],
): MediaModelOption | undefined {
  const normalized = modelRef.startsWith('general/') ? modelRef : `general/${modelRef}`;
  return getMediaModelOptions(generalModels).find(
    (model) => model.value === modelRef || model.value === normalized,
  );
}
