import type { ModelGroup } from '../../../types';

export const defaultModelGroups: ModelGroup[] = [
  // ========================================
  // 文本生成模型
  // ========================================
  {
    id: 'localllm',
    name: '本地大模型',
    description: '本地部署（Ollama / vLLM 等）',
    iconType: 'badge',
    badgeText: 'L',
    models: [
      {
        value: 'localllm/local',
        provider: 'localllm',
        label: '本地模型',
        description: '调用本地大模型服务地址',
        iconType: 'badge',
        badgeText: 'L',
        nodeTypes: ['ai-text'],
      },
    ],
  },
  {
    id: 'ppio',
    name: 'PPIO 派欧云',
    description: '高性价比、超弹性、低延迟',
    iconType: 'badge',
    badgeText: 'PP',
    models: [
      {
        value: 'minimax/minimax-m2.5-highspeed',
        provider: 'ppio',
        label: 'minimax-m2.5-highspeed',
        description: '更低延迟、更高性价比',
        iconType: 'badge',
        badgeText: 'MX',
        nodeTypes: ['ai-text'],
      },
      {
        value: 'qwen/qwen3.5-397b-a17b',
        provider: 'ppio',
        label: 'qwen3.5-397b',
        description: '阿里最强开源模型',
        iconType: 'badge',
        badgeText: 'QW',
        nodeTypes: ['ai-text'],
      },
      {
        value: 'deepseek/deepseek-v3.2',
        provider: 'ppio',
        label: 'deepseek-v3',
        description: '面向未来的新一代大模型',
        iconType: 'badge',
        badgeText: 'DS',
        nodeTypes: ['ai-text'],
      },
      {
        value: 'moonshotai/kimi-k2.5',
        provider: 'ppio',
        label: 'kimi-k2.5',
        description: '月之暗面最新版，超长上下文',
        iconType: 'badge',
        badgeText: 'KM',
        nodeTypes: ['ai-text'],
      },
    ],
  },
  {
    id: 'apimart',
    name: 'APIMart',
    description: '一个 API 搞定一切——节省 30-70%',
    iconType: 'badge',
    badgeText: 'AM',
    models: [
      // --- 文本模型 ---
      {
        value: 'apimart/gpt-5.4',
        provider: 'apimart',
        label: 'gpt-5.4',
        description: '极致逻辑与推理性能',
        iconType: 'badge',
        badgeText: 'OA',
        nodeTypes: ['ai-text'],
      },
      {
        value: 'apimart/kimi-k2-instruct',
        provider: 'apimart',
        label: 'Kimi K2 Instruct',
        description: 'APIMart text model',
        iconType: 'badge',
        badgeText: 'KM',
        nodeTypes: ['ai-text'],
      },
      // --- 图片模型 ---
      {
        value: 'apimart/nano-banana-2',
        provider: 'apimart',
        label: 'Nano banana 2',
        description: '新一代架构，兼顾细节与平衡',
        iconType: 'badge',
        badgeText: 'NB',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'apimart/nano-banana-pro',
        provider: 'apimart',
        label: 'Nano banana pro',
        description: '专业级画质，光影渲染深度优化',
        iconType: 'badge',
        badgeText: 'NP',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'apimart/nano-banana-dot',
        provider: 'apimart',
        label: 'Nano banana',
        description: '极速版，支持独特创意风格呈现',
        iconType: 'badge',
        badgeText: 'ND',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'apimart/gpt-image-2',
        provider: 'apimart',
        label: 'GPT image 2',
        description: 'OpenAI 图像生成模型，支持文生图与图生图',
        iconType: 'badge',
        badgeText: 'AM',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'apimart/qwen-image-2.0',
        provider: 'apimart',
        label: 'Qwen image 2.0',
        description: 'Qwen 图像生成，支持 1K/2K 与最多 6 张',
        iconType: 'badge',
        badgeText: 'AM',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'apimart/z-image-turbo',
        provider: 'apimart',
        label: 'Z-Image-Turbo',
        description: '轻量快速生图，支持 1K/2K 和智能改写',
        iconType: 'badge',
        badgeText: 'AM',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'apimart/wan2.7-image',
        provider: 'apimart',
        label: 'Wan 2.7',
        description: '支持文生图、图像编辑和多图参考',
        iconType: 'badge',
        badgeText: 'AM',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'apimart/seedream-4.0',
        provider: 'apimart',
        label: 'Seedream 4.0',
        description: '灵活图像功能，支持高分辨率',
        iconType: 'badge',
        badgeText: 'SD',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'apimart/seedream-4.5',
        provider: 'apimart',
        label: 'Seedream 4.5',
        description: '性能均衡的多模式图像生成',
        iconType: 'badge',
        badgeText: 'SD',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'apimart/seedream-5.0-lite',
        provider: 'apimart',
        label: 'Seedream 5.0',
        description: '轻量高效生图，支持 2K/3K 输出',
        iconType: 'badge',
        badgeText: 'SD',
        nodeTypes: ['ai-image'],
      },
    ],
  },
  {
    id: 'volcengine',
    name: '火山方舟',
    description: 'Ark Seedream 图像生成 API',
    iconType: 'badge',
    badgeText: 'V',
    models: [
      // --- 文本模型 ---
      {
        value: 'volcengine/doubao-seed-2-0-pro-260215',
        provider: 'volcengine',
        label: 'doubao-seed-2-0-pro',
        description: '适合复杂文本生成与推理',
        iconType: 'badge',
        badgeText: 'DB',
        nodeTypes: ['ai-text'],
      },
      {
        value: 'volcengine/doubao-seed-2-0-lite-260428',
        provider: 'volcengine',
        label: 'doubao-seed-2-0-lite',
        description: '适合高频文本任务',
        iconType: 'badge',
        badgeText: 'DL',
        nodeTypes: ['ai-text'],
      },
      // --- 图片模型 ---
      {
        value: 'volcengine/seedream-5.0',
        provider: 'volcengine',
        label: 'Seedream 5.0',
        description: '火山方舟原生生图，支持 2K/3K 输出',
        iconType: 'badge',
        badgeText: 'V',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'volcengine/seedream-4.5',
        provider: 'volcengine',
        label: 'Seedream 4.5',
        description: '高画质图像生成与多图参考',
        iconType: 'badge',
        badgeText: 'V',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'volcengine/seedream-4.0',
        provider: 'volcengine',
        label: 'Seedream 4.0',
        description: '经典 Seedream 生图，支持 1K/2K/4K',
        iconType: 'badge',
        badgeText: 'V',
        nodeTypes: ['ai-image'],
      },
    ],
  },

  // ========================================
  // 图片生成专用供应商
  // ========================================

  // --- GRSAI ---
  {
    id: 'grsai',
    name: 'GRSAI',
    description: '高性能 AI 图像生成服务',
    iconType: 'badge',
    badgeText: 'GR',
    models: [
      {
        value: 'grsai/gpt-image-2',
        provider: 'grsai',
        label: 'GPT image 2',
        description: 'OpenAI 图像生成模型',
        iconType: 'badge',
        badgeText: 'GR',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'grsai/nanobanana',
        provider: 'grsai',
        label: 'Nanobanana',
        description: '基础模型',
        iconType: 'badge',
        badgeText: 'GR',
        nodeTypes: ['ai-image'],
        nbFamily: 'nanobanana',
      },
      {
        value: 'grsai/nanobanana-pro',
        provider: 'grsai',
        label: 'NanobananaPRO',
        description: '专业增强模型',
        iconType: 'badge',
        badgeText: 'GR',
        nodeTypes: ['ai-image'],
        nbFamily: 'nanobanana-pro',
      },
      {
        value: 'grsai/nanobanana-2',
        provider: 'grsai',
        label: 'Nanobanana2',
        description: '第二代模型',
        iconType: 'badge',
        badgeText: 'GR',
        nodeTypes: ['ai-image'],
        nbFamily: 'nanobanana-2',
      },
    ],
  },

  // --- 即梦/Dreamina ---
  {
    id: 'dreamina',
    name: '即梦',
    description: '按版本直选，自动文生图/图生图',
    iconType: 'badge',
    badgeText: 'JM',
    models: [
      {
        value: 'dreamina/4.0',
        provider: 'dreamina',
        label: '即梦4.0',
        description: '无图文生图 / 单图图生图',
        iconType: 'badge',
        badgeText: 'JM',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'dreamina/4.1',
        provider: 'dreamina',
        label: '即梦4.1',
        description: '细节增强，生成更稳定',
        iconType: 'badge',
        badgeText: 'JM',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'dreamina/4.5',
        provider: 'dreamina',
        label: '即梦4.5',
        description: '综合性能均衡，推荐默认',
        iconType: 'badge',
        badgeText: 'JM',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'dreamina/5.0',
        provider: 'dreamina',
        label: '即梦5.0',
        description: '新版模型，画面表现更强',
        iconType: 'badge',
        badgeText: 'JM',
        nodeTypes: ['ai-image'],
      },
    ],
  },

  // --- RunningHUB 模型 ---
  {
    id: 'runninghub',
    name: 'RunningHUB模型',
    description: '模型 API：文生图/图生图/图片编辑',
    iconType: 'badge',
    badgeText: 'RH',
    models: [
      {
        value: 'runninghub/nanobanana',
        provider: 'runninghub',
        label: 'NanoBanana',
        description: '基础图像生成模型，版本可在模式中切换',
        iconType: 'badge',
        badgeText: 'NB',
        nodeTypes: ['ai-image'],
        nbFamily: 'nanobanana',
      },
      {
        value: 'runninghub/nanobanana-pro',
        provider: 'runninghub',
        label: 'BananaPRO',
        description: '专业级画质，版本可在模式中切换',
        iconType: 'badge',
        badgeText: 'BP',
        nodeTypes: ['ai-image'],
        nbFamily: 'nanobanana-pro',
      },
      {
        value: 'runninghub/nanobanana-2',
        provider: 'runninghub',
        label: 'Banana2',
        description: '新一代图像模型，版本可在模式中切换',
        iconType: 'badge',
        badgeText: 'B2',
        nodeTypes: ['ai-image'],
        nbFamily: 'nanobanana-2',
      },
      {
        value: 'runninghub/gpt-image-2',
        provider: 'runninghub',
        label: 'GPT image 2',
        description: 'OpenAI 图像生成模型，版本可在模式中切换',
        iconType: 'badge',
        badgeText: 'RH',
        nodeTypes: ['ai-image'],
        nbFamily: 'gpt-image-2',
      },
      {
        value: 'runninghub-model/youchuan-v81',
        provider: 'runninghub',
        label: 'Midjourney V8.1',
        description: 'RunningHub Midjourney 文生图 V8.1，支持主图和风格参考图',
        iconType: 'badge',
        badgeText: 'RH',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'runninghub-model/youchuan-v7',
        provider: 'runninghub',
        label: 'Midjourney V7',
        description: 'RunningHub Midjourney 文生图 V7，支持主图和风格参考图',
        iconType: 'badge',
        badgeText: 'RH',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'runninghub-model/youchuan-v6',
        provider: 'runninghub',
        label: 'Midjourney V6',
        description: 'RunningHub Midjourney 文生图 V6，支持主图、角色参考图和风格参考图',
        iconType: 'badge',
        badgeText: 'RH',
        nodeTypes: ['ai-image'],
      },
    ],
  },

  // --- RunningHUB 工作流 ---
  {
    id: 'runninghubwf',
    name: 'RunningHUB工作流',
    description: '工作流模板：替换/风格迁移，结果更可控',
    iconType: 'badge',
    badgeText: 'RW',
    models: [
      {
        value: 'runninghub/2041177685895946242',
        provider: 'runninghubwf',
        label: '人物替换图片编辑V3',
        description: '双图人物替换，支持目标/被替换图遮罩',
        iconType: 'badge',
        badgeText: 'RW',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'runninghub/2050313968069165058',
        provider: 'runninghubwf',
        label: '人物替换V2.1',
        description: '双图人物替换，支持目标/被替换图遮罩',
        iconType: 'badge',
        badgeText: 'RW',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'runninghub/1994718111704158209',
        provider: 'runninghubwf',
        label: '漫画转真人',
        description: '基于工作流把二次元角色转写实人像',
        iconType: 'badge',
        badgeText: 'RW',
        nodeTypes: ['ai-image'],
      },
      {
        value: 'runninghub/2050306122774532097',
        provider: 'runninghubwf',
        label: 'Qwen-图像编辑',
        description: '多图指令编辑，适合人物/产品一致性、文字修改与姿势/深度控制',
        iconType: 'badge',
        badgeText: 'RW',
        nodeTypes: ['ai-image'],
      },
    ],
  },
];
